### ISSUE TITLE
install.sh improvements

### ISSUE THREAD

**Issue by copenat** [wso2-ballerina/module-mongodb#43]
**Description:**
install.sh asks for Ballerina Home but it would already be set in a Linux environment. A more user-friendly installer would either use $BALLERINA_HOME or ask user to enter a value but default to the $BALLERINA_HOME. Either way would be better. Also - the install should show what is has done. ie which files has it copied where. 

Current install.sh behaviour:
[vamos@centos-vamos-lon1-01 tmp]$ sudo ./install.sh
Please enter Ballerina home: /usr/lib64/ballerina/ballerina-platform-0.983.0
Successfully installed MongoDB module!

**Comment by Manuri** [comment]
Thanks for reporting the issue @copenat. We'll look into the suggestions.

**Comment by kalaiyarasiganeshalingam** [comment]
Fixed in #54
