### ISSUE TITLE
Install.bat doesn't support ballerina home with spaces

### ISSUE THREAD

**Issue by wyldbill** [wso2-ballerina/module-mongodb#49]
**Description:**

Install.bat doesn't support ballerina home with spaces, Can't install with ballerina installed in C:\Program Files\Ballerina\ballerina-0.990.3, which is the default install location.

**Suggested Labels:**

install, Windows, install.bat

**Suggested Assignees:**

**Affected Product Version:**
0.8.1

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**
Install ballerina into default location : C:\Program Files\Ballerina\ballerina-0.990
Download and extract module-mongodb
run install.bat
attempt to provide ballerina install/home path

**Related Issues:**

**Comment by Manuri** [comment]
@wyldbill Can you try escaping the spaces?
eg: C:\Program^ Files\Ballerina\ballerina-0.990.3

**Comment by kalaiyarasiganeshalingam** [comment]
Fixed in #54
