### ISSUE TITLE
Example code won't compile under current (0.990.3) ballerina version.

### ISSUE THREAD

**Issue by wyldbill** [wso2-ballerina/module-mongodb#50]
**Description:**

Examples in module-mongodb/component/src/main/ballerina/Module.md will not compile. They give extraneous input errors when trying to match by type. This code:

> import ballerina/io;
> 
> public function main() {
> 	int|string bar = "foo";
> 	match bar {
> 		int i => io.println("I'm an int");
> 		string s => io.println("I'm a string");
> 	}
> }

will not compile. The examples contain match syntax directly analogous.

**Suggested Labels:**
 

**Suggested Assignees:**

**Affected Product Version:**
0.8.2-SNAPSHOT (from pom.xml)
ballerina version 0.990.3

**OS, DB, other environment details and versions:**    
Windows 10
Ballerina 0.990.3 via command line and Intellij (2018.3.5) Plugin (0.990.3)

**Steps to reproduce:**
try to compile above code.
Try to compile the example code in Module.md

**Related Issues:**

**Comment by wyldbill** [comment]
This also fails under ballerina 0.990.4-SNAPSHOT as of 3/20/2019

**Comment by Manuri** [comment]
We'll fix this as soon as possible. Thanks for reporting. Please refer the [README.md](https://github.com/wso2-ballerina/module-mongodb/blob/master/README.md) for an up to date sample.
