### ISSUE TITLE
Enhancement Request: Support replaceOne() 

### ISSUE THREAD

**Issue by wyldbill** [wso2-ballerina/module-mongodb#51]
**Description:**

Currently only update is supported for modifying documents. ReplaceOne will allow the wholesale replacement of a document instead of by field filters.

**Suggested Labels:**

Enhancement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Manuri** [comment]
We'll look into this. Thanks for the enhancement suggestion.

**Comment by kalaiyarasiganeshalingam** [comment]
Fixed in #54
